# Generated by Django 2.2.1 on 2019-07-15 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190706_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestemail',
            old_name='Email',
            new_name='email',
        ),
    ]
