# Generated by Django 2.2.1 on 2019-06-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20190627_0830'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billinig_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='billing.BillingProfile'),
        ),
    ]
