# Generated by Django 2.2.1 on 2019-06-27 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billinig_profile',
            new_name='billing_profile',
        ),
    ]
